{
 "title": "WebSocket Testing",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "query": {
     "query": "query_result(avg_over_time(ws_request_latency_distribution_count{}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "websocket request latency / μs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ws_request_latency_distribution_bucket{le=\"5\",application=\"${application}\"}[$__range]))",
     "legendFormat": "le=5"
    },
    {
     "expr": "sum(increase(ws_request_latency_distribution_bucket{le=\"10\",application=\"${application}\"}[$__range]))-sum(increase(ws_request_latency_distribution_bucket{le=\"5\",application=\"${application}\"}[$__range]))",
     "legendFormat": "le=10"
    },
    {
     "expr": "sum(increase(ws_request_latency_distribution_bucket{le=\"50\",application=\"${application}\"}[$__range]))-sum(increase(ws_request_latency_distribution_bucket{le=\"10\",application=\"${application}\"}[$__range]))",
     "legendFormat": "le=50"
    },
    {
     "expr": "sum(increase(ws_request_latency_distribution_bucket{le=\"100\",application=\"${application}\"}[$__range]))-sum(increase(ws_request_latency_distribution_bucket{le=\"50\",application=\"${application}\"}[$__range]))",
     "legendFormat": "le=100"
    },
    {
     "expr": "sum(increase(ws_request_latency_distribution_bucket{le=\"+Inf\",application=\"${application}\"}[$__range]))-sum(increase(ws_request_latency_distribution_bucket{le=\"100\",application=\"${application}\"}[$__range]))",
     "legendFormat": "le=Inf"
    }
   ]
  },
  {
   "title": "websocket request latency percentile / μs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ws_request_latency_percentile{quantile=\"0.5\",application=\"${application}\"}",
     "legendFormat": "P50"
    },
    {
     "expr": "ws_request_latency_percentile{quantile=\"0.9\",application=\"${application}\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "ws_request_latency_percentile{quantile=\"0.99\",application=\"${application}\"}",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "websocket rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(ws_request_latency_distribution_count{application=\"$application\"}[2m])",
     "legendFormat": "{{application}}"
    }
   ]
  }
 ]
}